### ISSUE TITLE
Plugin stopped working after running sometime. 

### ISSUE THREAD

**Issue by priyank6796** [emqx/emqx-auth-mongo#109]
- Here is my config for mongo auth plugin.

![image](https://user-images.githubusercontent.com/17333370/37957293-31ffb01e-31cb-11e8-8ea0-64955fdd33a1.png)
- **Problem in plugin**
- I enabled plugin using an Emqtt setting with my custom mongo config. it can able to authenticate a user using username and password which is stored in my collection named "mqtts". But after some time, it will be stopped working, Because of that user can able to log in using wrong username and password in the system. I also checked plugin running or not using the following command

> ./bin/emqttd_ctl plugins load emq_auth_mongo

- it will show that your plugin is already running. 
- It starts working fine if I restart the emqtt server.

**Comment by Maurocruzter** [comment]
I have a similar problem. I start the plugin but it does not verify the username and password, anyone can log in

**Comment by terry-xiaoyu** [comment]
This is mostly because of the `allow_anonymous` setting in emqx.conf, please verify that.
