### ISSUE TITLE
Can not connect to mongodb on AliCloud

### ISSUE THREAD

**Issue by DrmagicE** [emqx/emqx-auth-mongo#113]
2018-04-19 11:58:29 =ERROR REPORT====
** Generic server <0.318.0> terminating 
** Last message in was {'EXIT',<0.317.0>,killed}
** When Server state == {state,rsPrimary,"xxxxxxx-pub.mongodb.rds.aliyuncs.com",3717,<0.316.0>,<0.317.0>,[{pool_size,1},{max_overflow,0}],[{database,<<"xxx">>},{login,<<"xxx">>},{password,<<"xxxxxx">>}],undefined,20000,10000,1000,<0.451.0>,1}
** Reason for termination == 
** killed
2018-04-19 11:58:29 =CRASH REPORT====
  crasher:
    initial call: mc_monitor:init/1
    pid: <0.318.0>
    registered_name: []
    exception exit: {killed,[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}
    ancestors: [<0.317.0>,<0.316.0>,<0.314.0>,<0.313.0>,<0.311.0>,emq_auth_mongo_sup,<0.309.0>]
    messages: []
    links: [<0.451.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 566
  neighbours:
    neighbour: [{pid,<0.451.0>},{registered_name,[]},{initial_call,{mc_monitor,do_timeout,2}},{current_function,{mc_monitor,do_timeout,2}},{ancestors,[]},{messages,[]},{links,[<0.318.0>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,3},{reductions,1}]

**Comment by DrmagicE** [comment]
@terry-xiaoyu Here it is,thank you
## MongoDB Topology Type.
##
## Value: single | unknown | sharded | rs
auth.mongo.type = single

## Sets the set name if type is rs.
##
## Value: String
## auth.mongo.rs_set_name =

## MongoDB server list.
##
## Value: String
##
## Examples: 127.0.0.1:27017,127.0.0.2:27017...
auth.mongo.server = xxxxx-pub.mongodb.rds.aliyuncs.com:3717

## MongoDB pool size
##
## Value: Number
auth.mongo.pool = 8

## MongoDB login user.
##
## Value: String
auth.mongo.login = xxxx

## MongoDB password.
##
## Value: String
auth.mongo.password = xxxx

## MongoDB database
##
## Value: String
auth.mongo.database = xxx

## MongoDB write mode.
##
## Value: unsafe | safe
## auth.mongo.w_mode =

## Mongo read mode.
##
## Value: master | slave_ok
## auth.mongo.r_mode =

## MongoDB topology options.
auth.mongo.topology.pool_size = 1
auth.mongo.topology.max_overflow = 0
## auth.mongo.topology.overflow_ttl = 1000
## auth.mongo.topology.overflow_check_period = 1000
## auth.mongo.topology.local_threshold_ms = 1000
## auth.mongo.topology.connect_timeout_ms = 20000
## auth.mongo.topology.socket_timeout_ms = 100
## auth.mongo.topology.server_selection_timeout_ms = 30000
## auth.mongo.topology.wait_queue_timeout_ms = 1000
## auth.mongo.topology.heartbeat_frequency_ms = 10000
## auth.mongo.topology.min_heartbeat_frequency_ms = 1000

## Authentication query.
auth.mongo.auth_query.collection = mqtt_user

auth.mongo.auth_query.password_field = password

## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
auth.mongo.auth_query.password_hash = sha256

## sha256 with salt suffix
## auth.mongo.auth_query.password_hash = sha256,salt

## sha256 with salt prefix
## auth.mongo.auth_query.password_hash = salt,sha256

## bcrypt with salt prefix
## auth.mongo.auth_query.password_hash = salt,bcrypt

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mongo.auth_query.password_hash = pbkdf2,sha256,1000,20

auth.mongo.auth_query.selector = username=%u

## Enable superuser query.
auth.mongo.super_query = on

auth.mongo.super_query.collection = mqtt_user

auth.mongo.super_query.super_field = is_superuser

auth.mongo.super_query.selector = username=%u

## Enable ACL query.
auth.mongo.acl_query = off

auth.mongo.acl_query.collection = mqtt_acl

auth.mongo.acl_query.selector = username=%u

**Comment by DrmagicE** [comment]
@terry-xiaoyu Here it is,thank you
```## MongoDB Topology Type.
##
## Value: single | unknown | sharded | rs
auth.mongo.type = single

## Sets the set name if type is rs.
##
## Value: String
## auth.mongo.rs_set_name =

## MongoDB server list.
##
## Value: String
##
## Examples: 127.0.0.1:27017,127.0.0.2:27017...
auth.mongo.server = xxxxx-pub.mongodb.rds.aliyuncs.com:3717

## MongoDB pool size
##
## Value: Number
auth.mongo.pool = 8

## MongoDB login user.
##
## Value: String
auth.mongo.login = xxxx

## MongoDB password.
##
## Value: String
auth.mongo.password = xxxx

## MongoDB database
##
## Value: String
auth.mongo.database = xxx

## MongoDB write mode.
##
## Value: unsafe | safe
## auth.mongo.w_mode =

## Mongo read mode.
##
## Value: master | slave_ok
## auth.mongo.r_mode =

## MongoDB topology options.
auth.mongo.topology.pool_size = 1
auth.mongo.topology.max_overflow = 0
## auth.mongo.topology.overflow_ttl = 1000
## auth.mongo.topology.overflow_check_period = 1000
## auth.mongo.topology.local_threshold_ms = 1000
## auth.mongo.topology.connect_timeout_ms = 20000
## auth.mongo.topology.socket_timeout_ms = 100
## auth.mongo.topology.server_selection_timeout_ms = 30000
## auth.mongo.topology.wait_queue_timeout_ms = 1000
## auth.mongo.topology.heartbeat_frequency_ms = 10000
## auth.mongo.topology.min_heartbeat_frequency_ms = 1000

## Authentication query.
auth.mongo.auth_query.collection = mqtt_user

auth.mongo.auth_query.password_field = password

## Password hash.
##
## Value: plain | md5 | sha | sha256 | bcrypt
auth.mongo.auth_query.password_hash = sha256

## sha256 with salt suffix
## auth.mongo.auth_query.password_hash = sha256,salt

## sha256 with salt prefix
## auth.mongo.auth_query.password_hash = salt,sha256

## bcrypt with salt prefix
## auth.mongo.auth_query.password_hash = salt,bcrypt

## pbkdf2 with macfun iterations dklen
## macfun: md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512
## auth.mongo.auth_query.password_hash = pbkdf2,sha256,1000,20

auth.mongo.auth_query.selector = username=%u

## Enable superuser query.
auth.mongo.super_query = on

auth.mongo.super_query.collection = mqtt_user

auth.mongo.super_query.super_field = is_superuser

auth.mongo.super_query.selector = username=%u

## Enable ACL query.
auth.mongo.acl_query = off

auth.mongo.acl_query.collection = mqtt_acl

auth.mongo.acl_query.selector = username=%u
```

**Comment by terry-xiaoyu** [comment]
It looks like you had configured a `rs` and change the configuration back to single mode. Or the mongod you are connecting to is not of mode `single`. The configuration looks good, you could restart the plugin and try again.

**Comment by terry-xiaoyu** [comment]
Close the issue for now, if you have any problem, reopen it.
