### ISSUE TITLE
ACL does not check for client ID

### ISSUE THREAD

**Issue by romancardenas** [emqx/emqx-auth-mongo#121]
Hi everyone!
I am using the MongoDB auth-ACL plugin, and I detected something weird:
- In database, I save different ACLs depending not only on the username, but also on the client ID.
- In plugin configuration, I have set the following: `auth.mongo.acl_query.selector: username=%u,clientid=%c`

However, I have found out that the broker does not differ between different client IDs.
Is this functionality set or not?
In case it is possible to filter by client IDs, what am I doing wrong?

Thanks in advance.

**Comment by Gilbert-Wong** [comment]
Hi  romancardenas. Which branch of emq-auth-mongo did you use? The enterprise branch of emq-auth-mongo is well performed while other branches of emq-auth-mongo have some problems, please use enterprise branch.

**Comment by romancardenas** [comment]
I am using EMQ-docker, so, in order to use the enterprise branch I did the following:
- I forked emq-relx and changed line 31:
`dep_emq_auth_mongo    = git https://github.com/emqtt/emq-auth-mongo enterprise`
- Next, I forked emu-docker and modified the repository to be downloaded in order to point to my forked version of emq-relx

However, it does not seem to work as I expected: different clients that share username have the same permissions, even thought there are different documents for each of them in MongoDB

**Comment by huangdan** [comment]
@romancardenas, 
Has been fixed and released at v2.3.11.Please download the latest version for verification, if there is no problem, please close this issue.

**Comment by romancardenas** [comment]
Checked, it runs well.
Thank you very much for your attention
