### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by makoit** [emqx/emqx-auth-mongo#125]
My broker is runnning in a docker container with the latest image from : http://emqtt.io/downloads.

Additionally I also running my mongodb in a docker container with the latest image from: https://hub.docker.com/_/mongo/.

For inserting users  into the mongodb I'm using a browser based mongo client : https://hub.docker.com/r/mongoclient/mongoclient/.

With the browser shell of mongo client I followed the instructions:

```
use mqtt
db.createCollection("mqtt_user")
db.createCollection("mqtt_acl")
db.mqtt_user.ensureIndex({"username":1})

db.mqtt_user.insert({username: "user", password: "password", is_superuser: false})

db.mqtt_acl.insert({username: "user", publish: ["test1"], subscribe: ["test1"]})
```
Here you can see the collections:

![image](https://user-images.githubusercontent.com/42139290/44200916-3002b080-a148-11e8-9b95-72dab45c3448.png)
![image](https://user-images.githubusercontent.com/42139290/44200949-4577da80-a148-11e8-9a13-14d5651afe09.png)

After that I started the emq_auth_mongo plugin in the emq admin dashboard.
Here are my plugin configs:

![image](https://user-images.githubusercontent.com/42139290/44201033-7526e280-a148-11e8-9665-e5f222c508a9.png)

The I tried with mqtt box the connection. But I can't connect to the broker.

![image](https://user-images.githubusercontent.com/42139290/44201233-0ac27200-a149-11e8-9856-3944e06a6cf5.png)

Here you can see the broker logs:

`09:36:01.014 [error] Client(5b72d97c705985e7191a547a@172.17.0.1:46664): Username 'user' login failed for {{badmap,{error,timeout}},[{maps,get,[<<"password">>,{error,timeout},undefined],[{file,"maps.erl"},{line,192}]},{emq_auth_mongo,'-check/3-lc$^0/1-0-',2,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,52}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,543}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,216}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,324}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]}]}`

I can't find a mistake. I hope someone can help me.

**UPDATE:**

Changed the auth.mongo.server to internal ip of docker default bridge: 172.17.0.2:27017.
And I set with the rest api:

`{
    "key"   : "mqtt.allow_anonymous",
    "value" : "false"
}`

No my logs show this error:

`
06:57:03.592 [error] Client(5b753eed83f2c91def3e3e77@172.17.0.1:38864): Username 'admin' login failed for "No auth module to check!"
`

**Comment by makoit** [comment]
I fixed the problem.

The problem was the wrong ip adress -> it worked with 172.17.0.2. 
Because of the wrong ip adress the plugin was not able to connect correctly to the mongodb.
Found the ip adress with this docker command:
`$ docker network inspect bridge`


After some tests with my mqtt box this error:

`06:57:03.592 [error] Client(5b753eed83f2c91def3e3e77@172.17.0.1:38864): Username 'admin' login failed for "No auth module to check!"`

disappeared by themselves. I don't know why, but it works know.

**Comment by terry-xiaoyu** [comment]
@makoit Hi! Thanks for your effort on debugging the problem.

The error "No auth module to check!" basically told you that the client with `username=admin` can not be found from your mongo collections, so emq tried to go into the next auth plugin, e.g. the mysql or the pgsql plugin, but there's no such one. Maybe the mongo is the only auth plugin you have in your system.

**Comment by rajkiranjeet** [comment]
Hi
have you got solution for above problem ?

**Comment by Gilbert-Wong** [comment]
@rajkiranjeet Did you encounter the same issue?
