### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by WenXiuchun** [emqx/emqx-auth-mongo#136]
Makefile:29: erlang.mk: No such file or directory
make: *** No rule to make target 'erlang.mk'.  Stop.

**Comment by WenXiuchun** [comment]
wget https://erlang.mk/erlang.mk
and install erlang, still failed to make, this is error log:


==> rebar (compile)
==> rebar (escriptize)
Congratulations! You now have a self-contained script called "rebar" in
your current working directory. Place this script anywhere in your path
and you can use rebar to build OTP-compliant apps.
/home/ubuntu/emqx-auth-mongo
 DEP    cuttlefish (v2.2.0)
 DEP    mongodb (v3.0.7)
 DEP    ecpool (v0.3.0)
 DEP    clique (v0.3.11)
 DEP    emqx_passwd (v1.0)
make[1]: Entering directory '/home/ubuntu/emqx-auth-mongo/deps/emqx'
 DEP    jsx (undefined)
tar: /home/ubuntu/emqx-auth-mongo/.erlang.mk/hex/jsx.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/home/ubuntu/emqx-auth-mongo/erlang.mk:4959: recipe for target '/home/ubuntu/emqx-auth-mongo/deps/jsx' failed
make[1]: *** [/home/ubuntu/emqx-auth-mongo/deps/jsx] Error 2
make[1]: Leaving directory '/home/ubuntu/emqx-auth-mongo/deps/emqx'
erlang.mk:4388: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by WenXiuchun** [comment]
I installed the newest erlang, then make but still get this error:

src/emqx_acl_mongo.erl:20: can't find include lib "emqx/include/emqx.hrl"
erlang.mk:5300: recipe for target 'ebin/emqx_auth_mongo.app' failed
make[1]: *** [ebin/emqx_auth_mongo.app] Error 1
erlang.mk:5049: recipe for target 'app' failed
make: *** [app] Error 2

**Comment by Gilbert-Wong** [comment]
Ok , I will resolve it , thanks for your feedback.

**Comment by Gilbert-Wong** [comment]
Now it should be resolved @WenXiuchun
