### ISSUE TITLE
Unable to authenticate using bcrypt salt

### ISSUE THREAD

**Issue by syberkitten** [emqx/emqx-auth-mongo#78]
Took a moment to figure out how to set up the plugin to work properly.
which works with md5 hashed passwords.

The problem happens when I try to use bcrypt
with 10 cycle salted passwords:

here is my conf:
```.mongo.auth_query.password_hash = salt bcrypt 10```
tried also
```auth.mongo.auth_query.password_hash = salt bcrypt```
and
```auth.mongo.auth_query.password_hash = 10 salt bcrypt```

my bcrypt hashed password is:
$2a$10$xKRR.n9Mqej0jubXh9iFiOvywcpn9sBLiKalc6UVXI8guzqdc6M0.

The clear text password is:
TEST-PASS-USA

to validate online and generate bcrypt passwords:
https://www.dailycred.com/article/bcrypt-calculator

Getting this error:
```
2017-06-13 17:23:20.584 [info] <0.1389.0>@emqttd_protocol:trace:347 Client(undefined@127.0.0.1:55584): RECV CONNECT(Q0, R0, D0, ClientId=6dbb2d6f0e66ecde4706a14922e79304, ProtoName=MQTT, ProtoVsn=4, CleanSess=true, KeepAlive=60, Username=usa-user-test, Password=******)
2017-06-13 17:23:20.587 [error] <0.1389.0>@emqttd_protocol:process:214 Client(6dbb2d6f0e66ecde4706a14922e79304@127.0.0.1:55584): Username 'usa-user-test' login failed for {function_clause,[{emqttd_auth_mod,passwd_hash,[{salt,bcrypt},<<"TEST-PASS-USA">>],[{file,"src/emqttd_auth_mod.erl"},{line,55}]},{emq_auth_mongo,check_pass,3,[{file,"src/emq_auth_mongo.erl"},{line,65}]},{emq_auth_mongo,check,3,[{file,"src/emq_auth_mongo.erl"},{line,54}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,513}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,194}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,315}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]}]}
```

**Comment by syberkitten** [comment]
PS. Is there a guide somewhere how to run the whole EMQ project
locally from IntelliJ Idea and debug it?

I'm quite new to Erlang and would be much more efficient to Debug
the code and learn while doing so..

**Comment by syberkitten** [comment]
I think I might have found the issue.....
the default erlang bcrypt uses 12 cycle salt:

from:
https://github.com/smarkets/erlang-bcrypt

> default_log_rounds
> Sets the default number of rounds which define the complexity of the hash function. Defaults to 12.

While I'm trying to use 10 cycle.

I will test and report.

**Comment by turtleDeng** [comment]
@syberkitten https://github.com/smarkets/erlang-bcrypt/blob/master/src/bcrypt.app.src#L10

**Comment by syberkitten** [comment]
@turtleDeng yeah, thanks for pointing this out -) but it still does not solve my problem.

I'm creating a dummy user before the test with 12 cycle bcrypt salt (using nodejs bcrypt)
but still getting back: 

Connection refused: Bad username or password

**Comment by syberkitten** [comment]
Thank you for treating this seriously. :)
I would love to help, so if any more info or tests
give me a lead, and I'll try to check... 

Cheers 👍

**Comment by zacsonskaria** [comment]
I am getting similar error while using bcrypt with pgsql. Authentication fails while using bcrypt passwords. Tried 10 & 12 cycles, but no luck.
I am using emqtt stable version 2.2 on ubuntu 16.04.

**Comment by syberkitten** [comment]
@zacsonskaria It looks like the closest would be to use the [emq-auth-http](https://github.com/emqtt/emq-auth-http) plugin
and make rest HTTP calls for every connecting client, the rest endpoint
is responsible to Authenticate the user or not.

Of course it is more elegant to have the broker do it,|
but until it's fixed ...

**Comment by zacsonskaria** [comment]
@syberkitten Thats definitely a work around, but for me it will bring unnecessary overheads.
I have tried numerous combinations to somehow make bcrypt work (extracting hash and salt separately, changing cycles, prefix hash with salt etc) but nothing works. I heard bcrypt got enabled recently in 2.2 and wish it works even with some limitations.

**Comment by syberkitten** [comment]
@turtleDeng 
Is there any news on this issue?
Should I currently use the emq-auth-http plugin?

Perhaps the issue is simply resolved by allow a different
number of cycles for the bcrypt (currently it's 12)
but we are using 10.

12 cycles takes too long on our server infrastructure, 
so we would like to keep it at max 10.

this is the ref:
https://github.com/smarkets/erlang-bcrypt/blob/master/src/bcrypt.app.src#L10

**Comment by Bruce-sz** [comment]
I have the same problem, looking forward to the solution, thank you!

**Comment by turtleDeng** [comment]
@Bruce-sz Please provide error.log.

**Comment by Bruce-sz** [comment]
![image](https://user-images.githubusercontent.com/5813610/32227602-d8c71890-be19-11e7-9d29-a74a51a75b35.png)
![image](https://user-images.githubusercontent.com/5813610/32227588-cf29fbb8-be19-11e7-92d8-ffe81ccf8876.png)
![image](https://user-images.githubusercontent.com/5813610/32227543-b7973326-be19-11e7-9567-72e71642562c.png)

in emq_auth_mysql.conf 
=====but use bcrypt is failure, username="13701234567" login.=== 
## Password hash: plain, md5, sha, sha256, bcrypt
#auth.mysql.password_hash = sha256

## sha256 with salt prefix
## auth.mysql.password_hash = salt,sha256

## bcrypt with salt only prefix
auth.mysql.password_hash = salt,bcrypt

=====but use sha256 is ok, username="RTW-100-000002" login.===
## Password hash: plain, md5, sha, sha256, bcrypt
#auth.mysql.password_hash = sha256

## sha256 with salt prefix
## auth.mysql.password_hash = salt,sha256

## bcrypt with salt only prefix
auth.mysql.password_hash = salt,bcrypt


===============
I always restart emqtt server when re-setup config

**Comment by HJianBo** [comment]
@Bruce-sz The `salt` filed is incorrect! The **bcrypt** cipher-text structure is: 
```
$2a$(2 chars work cost)$(22 chars salt )(31 chars hash)
```
So **the cipher-text has contained salt!** 

The `salt` field of user "13701234567" should be `$2a$12$GgGmmP8xAMnummMdCeKn9.` (prefixed 29 characters)

Besides, you should ensure configuration files (emq_auth_mysql.conf) is correct:
```
## config auth fields is `password` and `salt`
auth.mysql.auth_query = select password, salt from mqtt_user where username = '%u' limit 1

## config auth method is `salt,bcrypt`
auth.mysql.password_hash = salt,bcrypt
```

**Comment by Bruce-sz** [comment]
@HJianBo Thanks!

**Comment by HJianBo** [comment]
In **EMQ 2.3** and **emq-auth-mongo**, support any **bcrypt** rounds. Because the server only checks whether the chiper-text is equal to the result which is encrypted by the plaintext & salt.

So you first have to make sure that the configuration file is correct (emq_auth_mongo.conf):
```
## config server 127.0.0.1:27017 or other address
auth.mongo.server = 127.0.0.1:27017

##  auth_query 
auth.mongo.auth_query.password_field = password,salt 

## bcrypt with salt prefix 
auth.mongo.auth_query.password_hash = salt,bcrypt
```

Then generate salt & cipher-text by **bcrypt**, and saving to mongodb. For example:
```
> use mqtt

# the clear password is TEST-PASS-USA
> db.mqtt_user.insert({username: 'test-mongo', password: '$2a$10$xKRR.n9Mqej0jubXh9iFiOvywcpn9sBLiKalc6UVXI8guzqdc6M0.', salt: '$2a$10$xKRR.n9Mqej0jubXh9iFiO'})
```

**Try login again ! 👻**

How generate salt & cipher-text? [by nodejs](https://github.com/kelektiv/node.bcrypt.js) 
Or taking the first 29 characters of the cipher-text

**Comment by emqplus** [comment]
@syberkitten @Bruce-sz @HJianBo Closed. Reopen it if any issue still.

**Comment by seksity** [comment]
> @syberkitten
> In **EMQ 2.3** and **emq-auth-mongo**, support any **bcrypt** rounds. Because the server only checks whether the chiper-text is equal to the result which is encrypted by the plaintext & salt.
> 
> So you first have to make sure that the configuration file is correct (emq_auth_mongo.conf):
> 
> ```
> ## config server 127.0.0.1:27017 or other address
> auth.mongo.server = 127.0.0.1:27017
> 
> ##  auth_query 
> auth.mongo.auth_query.password_field = password,salt 
> 
> ## bcrypt with salt prefix 
> auth.mongo.auth_query.password_hash = salt,bcrypt
> ```
> Then generate salt & cipher-text by **bcrypt**, and saving to mongodb. For example:
> 
> ```
> > use mqtt
> 
> # the clear password is TEST-PASS-USA
> > db.mqtt_user.insert({username: 'test-mongo', password: '$2a$10$xKRR.n9Mqej0jubXh9iFiOvywcpn9sBLiKalc6UVXI8guzqdc6M0.', salt: '$2a$10$xKRR.n9Mqej0jubXh9iFiO'})
> ```
> **Try login again ! 👻**
> 
> How generate salt & cipher-text? [by nodejs](https://github.com/kelektiv/node.bcrypt.js)
> Or taking the first 29 characters of the cipher-text

I using Windows10 with MongoDB 4.02 anb salt,bcrypt. it login fails as show log in emqx console as below:-

19:34:16.052 [error] MQTT(test-server@127.0.0.1:61244): Username 'test-mongo' login failed for {{badmatch,{error,{bcrypt,{"no such file or directory","bcrypt.app"}}}},[{emqx_passwd,hash,2,[{file,"src/emqx_passwd.erl"},{line,41}]},{emqx_auth_mongo,check_pass,4,[{file,"src/emqx_auth_mongo.erl"},{line,60}]},{emqx_auth_mongo,check,3,[{file,"src/emqx_auth_mongo.erl"},{line,50}]},{emqx_access_control,authenticate,3,[{file,"src/emqx_access_control.erl"},{line,71}]},{emqx_protocol,authenticate,2,[{file,"src/emqx_protocol.erl"},{line,613}]},{emqx_protocol,process_packet,2,[{file,"src/emqx_protocol.erl"},{line,289}]},{emqx_connection,handle_packet,2,[{file,"src/emqx_connection.erl"},{line,327}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]}]}

what the problem and how can i fix it?

**Comment by seksity** [comment]
Yes, I testing both EMQ 2.3.11 and EMQX 3.0 beta 3 (current version download from website) but unlucky it doesn’t works

**Comment by ngjaying** [comment]
@seksity From the error log: {{badmatch,{error,{bcrypt,{"no such file or directory","bcrypt.app"}}}, it is likely that your release does not have bcrypt or it is not compiled successfully. Could you check if there is bcrypt under deps folder and if bcrypt/ebin has the compiled beam files?

**Comment by seksity** [comment]
> @seksity From the error log: {{badmatch,{error,{bcrypt,{"no such file or directory","bcrypt.app"}}}, it is likely that your release does not have bcrypt or it is not compiled successfully. Could you check if there is bcrypt under deps folder and if bcrypt/ebin has the compiled beam files?
> 
> For the salt field, we will support bcrypt without "salt" field in the near future.

Thanks @ngjaying, cause of i download EMQX from website, so that means I need to git clone from Github and compile by make file instance, right?

great job for without "salt" field soon

**Comment by ngjaying** [comment]
> > @seksity From the error log: {{badmatch,{error,{bcrypt,{"no such file or directory","bcrypt.app"}}}, it is likely that your release does not have bcrypt or it is not compiled successfully. Could you check if there is bcrypt under deps folder and if bcrypt/ebin has the compiled beam files?
> > For the salt field, we will support bcrypt without "salt" field in the near future.
> 
> Thanks @ngjaying, cause of i download EMQX from website, so that means I need to git clone from Github and compile by make file instance, right?
> 
> great job for without "salt" field soon

@seksity windows version does not support bcrypt. I recommend you to use other OS or use WSL(Windows subsystem for linux). Thanks.

**Comment by terry-xiaoyu** [comment]
it seems that this problem has been solved.
