### ISSUE TITLE
v2.3-beta.4 - clients not connecting with valid username and password

### ISSUE THREAD

**Issue by shuaibakram** [emqx/emqx-auth-mongo#88]
The following is my config entry

`
auth.mongo.type = single`
`
auth.mongo.server = ds11****.mlab.com:17829
`
emqtt clients are not able to connect with their username and password
The live servers currently use v2.1.0-rc.2 version, which works fine.

**Comment by xerosanyam** [comment]
I solved this by setting `auth.mongo.server = 127.0.0.1:27017` and not `auth.mongo.server = 127.0.0.1:27017,127.0.0.2:27017`

**Comment by shuaibakram** [comment]
@xerosanyam Did you try with remote database? 
The issue comes when connecting to remote databases

**Comment by xerosanyam** [comment]
no. but `auth.mongo.server = 127.0.0.1:27017,127.0.0.2:27017` doesn't not let me connect with local DB.

**Comment by HJianBo** [comment]
Have you check the mongodb service, whether it login  successfully  with **mongo** command?

For example:
```
mongo --host 'remote_host' --port 27017 -u "name" -p "password"  --authenticationDatabase "mqtt"
```

**Comment by shuaibakram** [comment]
@HJianBo The login is successful with the above command

**Comment by shuaibakram** [comment]
Any update on this issue?

**Comment by arihantdaga** [comment]
I am getting a similar issue when keeping this confing

```
auth.mongo.type = rs
auth.mongo.server = MY_PRIVATE_IP1:21007,MY_PRIVATE_IP2:21007,MY_PRIVATE_IP3:21007

```

I am getting this in logs - 

```
08:25:24.224 [error] gen_server <0.1551.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
08:25:24.224 [error] CRASH REPORT Process <0.1551.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726

```

**Comment by terry-xiaoyu** [comment]
@arihantdaga hi, try to list all hosts of your replica set by ` db.isMaster()`, e.g. 
```
rs0:PRIMARY> db.isMaster().hosts
[ "localhost:27017", "localhost:27018", "localhost:27019" ]
```

And make sure it is the same as what you've configured in `etc/plugins/emq_auth_mongo.conf`:
```
auth.mongo.server = localhost:27017,localhost:27018,localhost:27019
```

Then restart the EMQ. Hope this works.

**Comment by DragWeb** [comment]
I have the same question, this is work! @terry-xiaoyu

**Comment by raoziwen** [comment]
Same question. Thank a lot!!! @terry-xiaoyu
